# Site settings
title: Debabrata Choudhury
description: 'A Hardcore Nix user'
url: 'https://lonewolf38.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
author:
  name: 'Debabrata Choudhury'
  email: sudodeba97.iiitbbsr@gmail.com
  twitter_username: itzmedeba
  facebook_username: debabratachoudhury17
  github_username:  LoneWolf38
  linkedin_username:  LoneWolf38
  instagram_username: itzmedeba
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
#permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
include: ['rice.md']
